### ISSUE TITLE
TOM sometimes randomly restarts itself

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#245] opened 2022-02-28 17:37 UTC

**Comment by adarshp** [comment] 2022-02-28 17:40
@kobus-barnard says - might be related to GNOME. We don't necessarily need GNOME -it's just a window manager.

**Comment by eduongAZ** [comment] 2022-03-16 19:06
ToM computer crashed and restarted itself while running the baseline task during test session today.

**Comment by adarshp** [comment] 2022-03-21 17:13
The GNOME error occurs on CAT as well. Perhaps CAT is also restarting but we don't notice.

Next steps
- Check if reducing ffmpeg framerate/resolution helps.
- look at system logs.

If all else fails, try re-installing OS on TOM.

**Comment by eduongAZ** [comment] 2022-03-21 23:01
CAT does not have ixgbe firmware error in `/var/log/kern.log`, but ToM does. @CalebUAz  and I fixed by installing ixgbe package downloaded by Kobus.

- `sudo bash`
- `cd /root/install/ixgbe_<version>/src`
- `make install`

**Comment by eduongAZ** [comment] 2022-03-21 23:51
With @CalebUAz, fixed the gnome error on ToM and CAT by installing nvidia-driver-520 through `Additional Drivers` GUI.

Test is currently performed to see if the problem persists by keeping a terminal open. If the terminal closes, a restart has occurred.

**Comment by eduongAZ** [comment] 2022-03-30 02:22
ToM restarted itself during the testing session. Chinmai and Rick believe that the issue is related to GPU after looking at system logs seeing GPU related messages.

**Comment by kobus-barnard** [comment] 2022-03-30 03:59
I'd check up on GPU driver versions. Systems are too sensitive to that.

**Comment by eduongAZ** [comment] 2022-03-30 18:41
Both ToM and CAT had the latest graphic drivers (nvidia-driver-510) but did not prevent the reboot.

**Comment by eduongAZ** [comment] 2022-03-30 22:34
Temporarily, we will use only one monitor on ToM until we can resolve the issue.

**Comment by adarshp** [comment] 2022-04-04 17:05
Eric/Chinmai: We will try connecting TOM and CAT directly to the wall instead of the power strip (extension cord with multiple sockets).

**Comment by adarshp** [comment] 2022-04-04 17:20
Kobus: There could be ways to get more info from the GPU - perhaps a NVidia tool/widget to see the GPU temperature, set the fan speed, etc. We used this to diagnose some issues on laplace.

Check logfiles, use the `uptime` command, etc.

We should also try moving the monitor to CAT and see if CAT inherits this problem.

**Comment by eduongAZ** [comment] 2022-04-05 19:25
- Plugged CAT computer power supply directly into the wall with an extension cord.
- Moved the extra monitor from ToM to CAT.
- Fixed firmware error reported in /var/log/kern.log with https://github.com/ml4ai/tomcat/issues/245#issuecomment-1074504394

**Comment by eduongAZ** [comment] 2022-04-08 22:58
Stressed the network today by streaming all data and running Minecraft for about 2 hours. ToM and CAT computers did not crash since running 3 days ago.

**Comment by rchamplin** [comment] 2022-04-08 23:09
Eric,
Very good.
Rick

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Eric Duong ***@***.***>
Sent: Friday, April 8, 2022 3:58:22 PM
To: ml4ai/tomcat ***@***.***>
Cc: Champlin, Rick - (rchamplin) ***@***.***>; Assign ***@***.***>
Subject: [EXT]Re: [ml4ai/tomcat] TOM sometimes randomly restarts itself (Issue #245)


External Email

Stressed the network today by streaming all data and running Minecraft for about 2 hours. ToM and CAT computers did not crash since running 3 days ago.

**Comment by eduongAZ** [comment] 2022-04-09 01:38
The power supply in ToM and CAT should be able to power ToM and CAT. I believe the problem might be that we did not provide enough power into the power supply in ToM, causing reboot due to power-usage spike.

Plugging CAT power supply directly into the wall instead of sharing a power strip with ToM seems to not cause any shutdown so far, even with both monitors running on CAT.

**Comment by kobus-barnard** [comment] 2022-04-09 03:02
OK. I am glad the problem has gone away, but stay skeptical about the cause.

**Comment by adarshp** [comment] 2022-04-11 17:23
Update: We are working on a script to parse the log files (or we may just use the `uptime` command).

**Comment by adarshp** [comment] 2022-04-11 17:23
Closing this issue now, will reopen if this becomes a problem again.

**Comment by eduongAZ** [comment] 2022-05-03 22:17
ToM restarted itself during the dry run today. A potential issue is ToM's auto-mounting set up causes ToM to shut down when there is a connection issue with NFS.

Currently, CAT computer does not have auto-mount of NFS and RAID0 set up, and has not restarted itself.

**Comment by kobus-barnard** [comment] 2022-05-03 23:51
Thanks for noticing this difference. We do not need automount, and it should be disabled, even though it may not be the cause of this issue.

**Comment by adarshp** [comment] 2022-05-11 22:21
Action items: 

- Get up to speed and understand log file rotation. Typical default in Unix is to keep log files for one month. This is configurable with settings. We should *not* throw any log files out until we are confident about the source of this issue. There are distinctive messages that are written to the log files when the system starts up.
- Check any power-saving, sleeping, and screen saving related settings. Are they exactly the same on TOM and CAT? If not, we should make sure they are identical.

**Comment by adarshp** [comment] 2022-05-11 22:26
Meta-point:

- Any observation of crashing should be reported in the form of a comment in this issue thread. Track any data that could give us any clues as to what is going on.

**Comment by adarshp** [comment] 2022-05-11 22:42
TODO:
- [ ] Consider studying the power and putting a UPS device in there. We can borrow one from another machine in GS.
- [ ] Do some Googling to find out what happens to a Linux box like TOM if there is not enough power? Will there be anything in the logs?
- [ ] Ask Thinkmate about this (Kobus) after we have a clean log of this happening.

Rick: In addition to examining logs, also note what activity was going on in the lab when the crash happened. See meta-point above.

**Comment by eduongAZ** [comment] 2022-05-13 17:56
Paulo and I observed the random restarts behavior on ToM in the lab. Nothing else was connected to the powerstrip other than ToM CPU and monitor.

During the first restart, we observed this behavior when Remmina was being used.

During the second restart, we observed that the UberScript was running.

**Comment by CalebUAz** [comment] 2022-05-18 21:20
Started a memtester around 10PM till now where it writes around 200GB data onto RAM and with 1 iteration it had no issues, it cleared all the tests.
![RAMtest](https://user-images.githubusercontent.com/90938130/169157446-0397ad47-5453-4479-91e2-459326d64bc5.png)

So it appears that RAM isn't an issue! 

Maybe swap out PSU with CAT to see if the issue still persists?

**Comment by kobus-barnard** [comment] 2022-05-18 21:56
Thanks for the report. 

Let's keep the language precises. The RAM is likely not the issue.

Swapping the PS is a good idea. However, let me contact ThinkMate first. I will cc some of you.

**Comment by eduongAZ** [comment] 2022-06-04 23:57
I commented out the lines in `/etc/fstab` in ToM that automatically connect to NFS shared drive on CAT and automatically mount the `/data` folder. This is to ensure that ToM and CAT are set up identically to rule out some potential causes of ToM restarting.

From now on, if ToM and/or CAT reboots, the following steps must be followed to mount RAID0 drive (the `/data` folder) and manually mount the NFS shared drive:

If ToM is rebooted:
1. Mount RAID0 drive with`mount /dev/md0 /data/tom`
2. Mount NFS shared drive with `mount -o rw -t nfs 192.168.0.25:/data/cat /data/cat`

If CAT is rebooted:
1. Mount RAID0 drive with`mount /dev/md0 /data/cat`
2. Mount NFS shared drive with `mount -o rw -t nfs 192.168.0.24:/data/cat /data/tom`

If both ToM and CAT rebooted:
1. Mount RAID0 drive on ToM computer with`mount /dev/md0 /data/tom`
2. Mount RAID0 drive on CAT computer with`mount /dev/md0 /data/cat`
3. Restart NFS server on ToM with `systemctl restart nfs-kernel-server`
4. Restart NFS server on CAT with `systemctl restart nfs-kernel-server`
5. Mount CAT's NFS shared drive to ToM with `mount -o rw -t nfs 192.168.0.25:/data/cat /data/cat`
6. Mount ToM's NFS shared drive to CAT with `mount -o rw -t nfs 192.168.0.24:/data/cat /data/tom`

**Comment by eduongAZ** [comment] 2022-06-15 02:31
We have not observed the random reboot problem today.

**Comment by eduongAZ** [comment] 2022-06-22 02:32
The issue will be re-opened when we observe the restarting behavior again.

**Comment by rchamplin** [comment] 2023-01-04 21:32
CAT has now exhibited the same problem, at least two times, of restarting when someone touches the top of the computer near the USB connectors or the reset button. So now, TOM and CAT have exhibited the same restarting problem.

I have seen the problem multiple times now being initiated the same way on both servers, someone walks up and the first thing they touch is the top of TOM or CAT near the USB connectors or a cable plugged into one of the USB connectors.

My analysis:
After seeing it happen multiple times and having it happen to me several times, I strongly suspect that it is a static shock traveling down into the top USB Connector's and the Reset Button's little circuit board and activating the reset circuity. It is obvious that there is a lot of static picked up when someone walks across the control room floor. It has happened to all of us lots of times. You walk across the control room floor and the first conductive thing (or person) you touch, there is a noticeable static shock. If the first thing you touch is TOM or CAT on the top near or on the USB connectors, that is when it seems we initiate the restart problem.

Corrective action:
Months ago, I placed a sign on TOM covering the top USB connectors that read "Do Not Touch" and I pushed the server back a couple of inches from the edge of the table. Since putting the sign on, TOM has not randomly restarted itself.
About a month ago, I removed the experiment participant's Earbuds that were plugged into the USB connectors on the top of CAT for charging between experiments. I setup the Earbuds to charge on a stand alone USB HUB plugged into a power adaptor and place away from the servers. After moving the Earbuds, there is no longer a routine reason to touch CAT and I pushed CAT a few inches back away from the edge of the table. Since moving the Earbuds telling everyone not to touch CAT, there has not been an incident of CAT randomly restarting itself.

Going forward:
I am planning to place/stick a grounding strip on the table around TOM and CAT (I have the materials to make the strips) and make signs/post that reads something like "If you need to touch TOM or CAT, please ground yourself to the grounding strips before touching the Servers".

I think this resolves this problem and the issue can be closed for now.

**Closed** 2023-01-04 21:34 UTC
Labels: bug, Priority: High

**Comment by adarshp** [comment] 2023-01-04 21:42
Thank you @rchamplin for the analysis and implementing a solution!
